# Set local dev port for Netlify CLI
[dev]
  port = 8888
# Netlify Scheduled Function for Faire Orders
[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[functions."faire-get-orders-cron"]
  schedule = "*/15 * * * *" # every 15 minutes

[functions."shippo-get-orders-cron"]
  schedule = "*/15 * * * *" # every 15 minutes

[functions."shippo-remove-fulfilled-orders"]
  schedule = "*/15 * * * *" # every 15 minutes

[functions."faire-sync-inventory-cron"]
  schedule = "*/15 * * * *" # every 15 minutes

[functions."etsy-sync-inventory-cron"]
  schedule = "*/15 * * * *" # every 15 minutes

[functions."notifications-cron"]
  schedule = "0 9 * * *" # every day at 9:00 AM