# Set local dev port for Netlify CLI
[dev]
  port = 8888
# Netlify Scheduled Function for Faire Orders
[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[functions."faire-get-orders-cron"]
  schedule = "*/15 * * * *" # every 15 minutes

[functions."shippo-get-orders-cron"]
  schedule = "*/15 * * * *" # every 15 minutes

[functions."faire-sync-inventory-cron"]
  schedule = "*/15 * * * *" # every 15 minutes

[functions."etsy-sync-inventory-cron"]
  schedule = "*/15 * * * *" # every 15 minutes

[functions."notifications"]
  schedule = "0 9-17 * * 1-5" # every hour during business hours (9 AM - 5 PM), Monday to Friday